### ISSUE TITLE
Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f87772f10>: Failed to establish a new connection: [Errno 111] Connection refused'))"}

### ISSUE THREAD

**Issue by koep** [RedHat-EMEA-SSA-Team/hetzner-ocp4#149]
Hi all,

People are hitting https://github.com/kubernetes-client/python/issues/1333 left and right. At this point in time, the only work around seems to be to manually downgrade the package via `pip3`:

```
# pip3 install --upgrade kubernetes==11.0.0
```

We are still investigating details, but this might already be useful for folks.

cc @iboernig @ardaoralde @bcygan

**Comment by koep** [comment]
Likely because we use the latest `openshift` python module [source](https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/master/ansible/roles/openshift-4-cluster/tasks/prepare-host-CentOS-8.yml#L20) which pulls the latest `kubernetes` python module [source](https://github.com/openshift/openshift-restclient-python/blob/master/requirements.txt#L2). We might want to pin the OpenShift package to the latest working version.

**Comment by rbo** [comment]
Mh on RHEL 8 systems we can enable the repo `rhocp-4.6-for-rhel-8-x86_64-rpms`

```
$ subscription-manager repos --enable=rhocp-4.6-for-rhel-8-x86_64-rpms
Repository 'rhocp-4.6-for-rhel-8-x86_64-rpms' is enabled for this system.
$ dnf install python3-openshift.noarch
Updating Subscription Management repositories.
Last metadata expiration check: 0:00:43 ago on Fri 18 Dec 2020 05:38:12 PM CET.
Dependencies resolved.
====================================================================================================
 Package                  Arch   Version                     Repository                        Size
====================================================================================================
Installing:
 python3-openshift        noarch 1:0.11.2-1.el8              rhocp-4.6-for-rhel-8-x86_64-rpms  57 k
Installing dependencies:
 python3-cachetools       noarch 3.1.0-1.el8ost              rhocp-4.6-for-rhel-8-x86_64-rpms  33 k
 python3-certifi          noarch 2018.10.15-4.el8ost         rhocp-4.6-for-rhel-8-x86_64-rpms  17 k
 python3-dictdiffer       noarch 0.7.1-2.el8ost              rhocp-4.6-for-rhel-8-x86_64-rpms  33 k
 python3-google-auth      noarch 1.3.0-1.el8ost              rhocp-4.6-for-rhel-8-x86_64-rpms  82 k
 python3-kubernetes       noarch 11.0.0-1.el8                rhocp-4.6-for-rhel-8-x86_64-rpms 1.2 M
 python3-pip              noarch 9.0.3-18.el8                rhel-8-for-x86_64-appstream-rpms  20 k
 python3-pyasn1           noarch 0.3.7-6.el8                 rhel-8-for-x86_64-appstream-rpms 126 k
 python3-pyasn1-modules   noarch 0.3.7-6.el8                 rhel-8-for-x86_64-appstream-rpms 110 k
 python3-rsa              noarch 4.6-1.el8                   rhocp-4.6-for-rhel-8-x86_64-rpms  59 k
 python3-ruamel-yaml      x86_64 0.15.41-4.el8ost            rhocp-4.6-for-rhel-8-x86_64-rpms 308 k
 python3-setuptools       noarch 39.2.0-6.el8                rhel-8-for-x86_64-baseos-rpms    163 k
 python3-string_utils     noarch 0.6.0-4.el8ost              rhocp-4.6-for-rhel-8-x86_64-rpms  20 k
 python3-websocket-client noarch 0.54.0-1.el8ost             rhocp-4.6-for-rhel-8-x86_64-rpms  61 k
 python36                 x86_64 3.6.8-2.module+el8.1.0+3334+5cb623d7
                                                             rhel-8-for-x86_64-appstream-rpms  19 k
Enabling module streams:
 python36                        3.6

Transaction Summary
====================================================================================================
Install  15 Packages

Total download size: 2.2 M
Installed size: 25 M
```

I will try this...

**Comment by rbo** [comment]
Sadly I don't have a Centos Server running. I applied a fix to branch rbohne/devel (b08fe14185f8f4ce8a3b99f81328dbb0db4eb318)... Maybe some have time to test it...

**Comment by rbo** [comment]
On a fresh installed Hetzner Centos Image, there are RPM packages for `python3-openshift` available. Let's test it...

Enabled repos by default:

```bash
# dnf repolist --enabled
repo id                                               repo name
appstream                                             CentOS Linux 8 - AppStream
baseos                                                CentOS Linux 8 - BaseOS
epel                                                  Extra Packages for Enterprise Linux 8 - x86_64
epel-modular                                          Extra Packages for Enterprise Linux Modular 8 - x86_64
extras                                                CentOS Linux 8 - Extras
```

**Comment by rbo** [comment]
Damn:
```
$ rpm -qa |grep kubern
python3-kubernetes-12.0.1-1.el8.noarch
```

**Comment by rbo** [comment]
Fixed in devel branch, will be merged into master via PR #159

**Comment by jmazzitelli** [comment]
How does one pick up this fix?

I have this and I still have the problem:

```
pip3 list | grep -E "openshift|kubernetes"
kubernetes           12.0.1
openshift            0.12.0
```
